<?php
$this->dojo()->enable(); ?>

<script type="text/javascript">
    dojo.require("dijit.form.Form");
    dojo.require("dijit.form.Button");
    dojo.require("dijit.Dialog");
    dojo.require("dijit.form.TextBox");
    dojo.require("dijit.form.DateTextBox");
    dojo.require("dijit.form.TimeTextBox");
    dojo.addOnLoad(function() {
        var loginDialog = dijit.byId("formLogin");
        dijit.byId("formLogin").show();
    });
</script>

<div dojoType="dijit.Dialog" id="formLogin" title="Login..." style="display: none">
	<form dojoType="dijit.form.Form">
		<script type="dojo/event" event="onSubmit" args="e">
			dojo.stopEvent(e);
			if (!this.isValid()) {
        dijit.byId('formLogin').set('title','Invalid email or password');
			  return;
			}
       var email = dijit.byId("email").get('value');
       var pw = dijit.byId("password").get('value');
			 dojo.xhrPost({
			  url:"/auth/login/login",
			  sync: true,
			  content:{email: email, password: pw},
			  preventCache:true,
			  handleAs:"json",
			  handle: function(response, ioArgs) {
			   auth_successful = dojo.fromJson(ioArgs.xhr.responseText);
         if (auth_successful == "true") {
				  dijit.byId('formLogin').hide();
          window.location = '/';
         } else {
          dijit.byId('formLogin').set('title','Rejected email or password');
         }
			  },
			   error: function(response, ioArgs) {
			   console.debug("Error status:" + ioArgs.xhr.statusText);
			  }
			 });
    </script>
		<div class="dijitDialogPaneContentArea">
			<table>
				<tr>
					<td><label for='email'> Email: </label>
						<div dojoType="dijit.form.ValidationTextBox" id="email" name="email" required="true" style="float:right"></div>
					</td>
				</tr>
				<tr>
					<td><label for='password'> Password: </label>
						<div dojoType="dijit.form.ValidationTextBox" id="password" type="password" name="password" required="true" style="float:right"></div>
					</td>
				</tr>
			</table>
		</div>
		<div class="dijitDialogPaneActionBar">
			<button dojoType="dijit.form.Button" id="buttonSubmit" type="submit">Login</button>
			<button dojoType="dijit.form.Button" type="button"
			onClick="dijit.byId('formLogin').hide();window.location='/';">Cancel</button>
			<label for='buttonRegister'> Not Registered? </label>
			<button dojoType="dijit.form.Button" type="button" id="buttonRegister"
			onClick="dijit.byId('formLogin').hide();window.location='/admin/registration';">Sign Up</button>
		</div>
	</form>
</div>
