<div class="entity">
<div class='userProfile'>
<h2>User Profile: <?php echo $this->first?> <?php echo $this->middle?> <?php echo $this->last?></h2>
  <hr>
  <p><img src="/images/avatars/<?php echo $this->avatar?>" /></p>
  <p><strong>Occupation:</strong> <?php echo $this->occupation?></p>
  <p><strong>Bio:</strong> <?php echo $this->bio_text?></p>
  <p><strong>Website:</strong> <a href="<?php echo $this->website?>"><?php echo $this->website?></a></p>
  <p></p>
  <div class="clearfix"></div>
</div>
</div>

