    <div class="content">
  <div class="sidebarLt">
    <?php echo $this->getMenu('main') ?>
  </div>
    <div class="sidebarRt">
        <div class="sideWrap clearfix">
            <div class="contribs">
                <h3>Search</h3>
                <hr>
                <div class="aboutWrap">
                    <div class="searchBox">
                        <?php echo $this->searchForm;?>
                    </div><!-- end searchBox -->
                </div><!-- end aboutWrap -->
            </div><!-- end contribs -->
        </div><!-- end sideWrap -->
        <?php echo $this->partial('sidesocial.phtml', array())?>
        <div id="logform">
            <?php echo $this->form?>
        </div><!-- end logform -->
        <?php echo $this->partial('sidebar.phtml', array('lc' => $this->lc))?>
    </div><!-- end sidebarRt -->
    <div class="mainTitle">
        <img id='logo' src="/images/logo2.png" height="160" width="100%"></img>
    </div><!-- end mainTitle -->
    <div class="twoCol">
        <?php echo $this->layout()->content?>
    </div> <!-- end midcol -->
    <div class="clearfix"></div>
    </div>
