<div class="content">
  <div class="sidebarLt">
    <?php echo $this->getMenu('main') ?>
  </div>
    <div class="sidebarRt">
        <div class="sideWrap clearfix">
            <div class="contribs">
                <h3>Search</h3>
                <hr>
                <div class="aboutWrap">
                    <div class="searchBox">
                        <?php echo $this->searchForm;?>
                    </div><!-- end searchBox -->
                </div><!-- end aboutWrap -->
            </div><!-- end contribs -->
        </div><!-- end sideWrap -->
    </div><!-- end sidebarRt -->
    <div class="mainTitle">
        <img id='logo' src="/images/logo2.png" alt="logo" />
    </div><!-- end mainTitle -->
    <div class="twoCol">
        <?php echo $this->layout()->content?>
    </div> <!-- end twoCol -->
    <div class="clearfix"></div>
</div>
